### ISSUE TITLE
Fix non-root path in client

### ISSUE THREAD

**Issue by firelion9** [spbu-math-cs/roomkn#113]
Сейчас на клиенте существует только /, все переходы на гругие URL происходят фиктивно, поэтому после перезагрузки вылетает 404. Это надо пофиксить

**Comment by robozmey** [comment]
У меня всё ок, а вот при деплое на докере эта проблема вылезает

**Comment by robozmey** [comment]
npx serve build -s

-s flag Rewrite all not-found requests to `index.html`
