### ISSUE TITLE
Until time before From time in reservation form

### ISSUE THREAD

**Issue by robozmey** [spbu-math-cs/roomkn#149]
![Image](https://github.com/spbu-math-cs/roomkn/assets/33569237/00b9d24d-d767-4fce-9c1e-e03e931e1930)

**Comment by PaulRalnikov** [comment]
Разве это не таска для БД? Кажется, что подобная логика должна отрабатывать именно там

**Comment by PaulRalnikov** [comment]
Или нужно поправить отображение на таймлайне?
