### ISSUE TITLE
Fix cookie same-site headers

### ISSUE THREAD

**Issue by firelion9** [spbu-math-cs/roomkn#199]
В хроме передача куки блокируется из-за некорректных заголовков.

![Image](https://github.com/spbu-math-cs/roomkn/assets/45895611/f72be332-f109-499b-bb69-c6a75e873873)

**Comment by makselivanov** [comment]
https://stackoverflow.com/questions/67821709/this-set-cookie-didnt-specify-a-samesite-attribute-and-was-default-to-samesi

Согласно этому стековерлоу ответу, нам нужны шифровать соединение, чтобы это починить
