### ISSUE TITLE
Partial PUT (PATCH)

### ISSUE THREAD

**Issue by Bupaheh** [spbu-math-cs/roomkn#256]

**Comment by Bupaheh** [comment]
![image](https://github.com/spbu-math-cs/roomkn/assets/71063977/3c4c3cf0-7f5c-4d86-b760-82cb91ffade2)

**Comment by makselivanov** [comment]
Я предлагаю вместо того, чтобы делать частичный PUT, а согласно стандарам сделать PATCH тогда

**Comment by makselivanov** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH
